# ----
# Site

title: Scottish Enterprise Customer Insights
# url: "https://scotentsd.github.io/edition-jekyll-template/search/?q=friends"
url: "https://scotentsd.github.io/edition-jekyll-template/search/?q=friends"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Scottish Enterprise Research Insights.
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Insights
  links:
    - https://github.com/scotentSD/insights

# -----
# Build

timezone: Etc/UTC

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
      _options:
        content:
          width: 800
          height: 2000
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
  
  
prose:
  rooturl: ''
  siteurl: 'http://scotentSD.github.io/insights/'
  relativeLinks: 'http://scotentSD.github.io/insights/links.jsonp'
  media: 'files'
  ignore: [links.jsonp,  _config.yml,  media,  assets,  _sass,  _layouts, _includes, _flist, _drafts, images,_plugins, css, scripts, mktest, data.json, data2.json, data2.jsonp, timeline.css, links_copy.jsonp, testrounds, js, timelinelight.md, timelinelight2.md, timelinelight3.md,  timeline_summary2.md, timeline_summary.md, timeline.md]
  metadata:
   _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "post"
    - name: "type"
      field:
        element: "select"
        label: "Type"
        placeholder: ""
        options:
          - name: " lab "
            value: "lab"
          - name: " online "
            value: "online"
          - name: " a11y "
            value: "a11y"
          - name: " other "
            value: "other"
          - name: " partner"
            value: "partner"
    - name: "phase"
      field:
        element: "select"
        label: "Phase"
        placeholder: ""
        options:
         - name: "discovery"
           value: "discovery"
         - name: "alpha"
           value: "alpha"
         - name: "beta"
           value: "beta"
         - name: "live"
           value: "live"
    - name: "initials"
      field:
        element: "text"
        label: "Initials"
        value: ""
    - name: "display_date"
      field:
        element: "text"
        label: "Display_Date"
        value: ""
    - name: "tltitle"
      field:
        element: "text"
        label: "Title"
        value: ""
    - name: "return_url"
      field:
        element: "hidden"
        value: "https://scotentsd.github.io/insights/timeline/"
